//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.Marketings = new HashSet<Marketing>();
        }
    
        public bool isconsultant { get; set; }
        public int id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public System.DateTime optstartdate { get; set; }
        public string technology { get; set; }
        public string instructor { get; set; }
        public string optstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketing> Marketings { get; set; }
    }
}
